[workspace]
resolver = "3"
members = [
  "crates/soroban-test-helpers",
  "crates/example",
  "crates/soroban-rs",
  "crates/soroban-rs-macros"
]
default-members = ["crates/soroban-test-helpers"]

[workspace.package]
edition = "2021"
rust-version = "1.93.0" # MSRV (for stellar-rpc-client - others need 1.91)
repository = "https://github.com/OpenZeppelin/soroban-helpers"
documentation = "https://github.com/OpenZeppelin/soroban-helpers"
description = "A collection of helpers for writing tests for Soroban contracts"
license = "MIT"
keywords = ["soroban", "stellar", "blockchain", "smart-contracts", "testing"]

[workspace.dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
soroban-sdk = "26.0.0"
tokio = { version = "1.52.0", features = ["sync", "io-util", "macros", "rt", "time"] }
wasi-stellar-rpc-client = { version = "26.0.0-rc.3" }
stellar-xdr = { version = "26.0.0", features = ["serde", "serde_json"] }
stellar-strkey = "0.0.16"
ed25519-dalek = "2.1.1"
sha2 = "0.10.8"
rand = "0.9.0"
hex = "0.4.3"
dotenv = "0.15.0"
async-trait = "0.1.88"
tempfile = "3.10.1"

# members
wasi-soroban-test-helpers = { path = "crates/soroban-test-helpers" }
wasi-soroban-rs = { path = "crates/soroban-rs" }
wasi-soroban-rs-macros = { path = "crates/soroban-rs-macros", version = "0.2.7" }